import { Project, Category, Importance } from './types';

export const PROJECTS: Project[] = [
  {
    id: 'rescute-animals',
    title: 'Rescute Animals',
    categories: [Category.VIDEOGAMES],
    importance: Importance.NORMAL,
    year: '2016-2017',
    sortYear: 2017,
    description: 'Video game project focused on animal rescue. An interactive adventure designed to raise awareness and entertain through exploration and salvage mechanics.',
    imageUrl: '/images/projects/rescute-animals.jpg',
    techStack: ['Unity', 'C#', 'Game Dev', 'Indie Game', '3D'],
    link: 'https://youtu.be/E_y9G5eyMaU'
  },
  {
    id: 'prototipo-cirugia-fibao',
    title: 'Cirugía Virtual Fibao',
    categories: [Category.EXTENDED_REALITY, Category.SIMULATION],
    importance: Importance.NORMAL,
    year: '2020-2021',
    sortYear: 2021,
    description: 'Virtual Reality surgical simulation prototype developed for Fibao. An immersive tool for medical training and complex procedure planning.',
    imageUrl: '/images/projects/prototipo-cirugia-fibao.jpg',
    techStack: ['Unity', 'VR', 'Medical Simulation', 'HealthTech', 'Oculus'],
    link: 'https://youtu.be/NDRkGpJTPXo'
  },
  {
    id: 'tarot-q-vr',
    title: 'Tarot Q VR',
    categories: [Category.EXTENDED_REALITY],
    importance: Importance.CASUAL,
    year: '2020',
    sortYear: 2020,
    description: 'Immersive Tarot reading experience in Virtual Reality. A mystical environment created that allows users to interact with cards and symbology in a 3D space.',
    imageUrl: '/images/projects/tarot-q-vr.jpg',
    techStack: ['Unity', 'VR', 'Experience', 'Oculus', 'Interactive'],
    link: 'https://youtu.be/gomvhLkUcnU'
  },
  {
    id: 'plaza-talavera-vr',
    title: 'Plaza del Pan de Talavera en VR',
    categories: [Category.EXTENDED_REALITY, Category.SIMULATION],
    importance: Importance.CASUAL,
    year: '2020',
    sortYear: 2020,
    description: 'Virtual historical reconstruction of the Plaza del Pan de Talavera de la Reina. A journey to the past using Virtual Reality that allows exploration of architectural heritage.',
    imageUrl: '/images/projects/plaza-talavera-vr.jpg',
    techStack: ['Unity', 'VR', 'Photogrammetry', 'History', 'Heritage'],
    link: 'https://youtu.be/LK9gg4TdhLI'
  },
  {
    id: 'virtual-feet',
    title: 'Virtual Feet',
    categories: [Category.EXTENDED_REALITY],
    importance: Importance.TOP,
    year: '2017-2020',
    sortYear: 2019,
    description: 'Presentation of the Virtual Feet system, a hardware and software solution for locomotion in Virtual Reality. Project focused on solving infinite movement in limited spaces.',
    imageUrl: '/images/projects/virtual-feet.jpg',
    techStack: ['Unity', 'VR Hardware', 'Locomotion', 'Virtual Reality', 'Innovation'],
    link: 'https://youtu.be/P5FoPwcj6OY'
  },
  {
    id: 'vueling-game',
    title: 'Vueling Game',
    categories: [Category.VIDEOGAMES],
    importance: Importance.NORMAL,
    year: '2024',
    sortYear: 2024,
    description: 'Runner-type video game developed for an interactive installation with the Vueling airline. An adver-gaming experience designed for events and user participation.',
    imageUrl: '/images/projects/vueling-game.jpg',
    techStack: ['Unity', 'Runner', 'VideoGame', 'Interactive Installation', 'C#'],
    link: 'https://youtu.be/Pfcwj29Tak4'
  },
  {
    id: 'mannaz',
    title: 'Mannaz',
    categories: [Category.VIDEOGAMES],
    importance: Importance.CASUAL,
    year: '2021-2024',
    sortYear: 2024,
    description: 'Simultaneous turn-based multiplayer strategy game about battles between wizard schools. Combines tactics, team management, and deep customization of spells and runes.',
    imageUrl: '/images/projects/mannaz.jpg',
    techStack: ['Unity', 'Multiplayer', 'Strategy', 'Steam', 'Turn-Based'],
    link: 'https://store.steampowered.com/app/1695450/Mannaz/?l=spanish'
  },
  {
    id: 'space-creator-editor',
    title: 'Space Creator: World Editor',
    categories: [Category.VIDEOGAMES, Category.EXTENDED_REALITY],
    importance: Importance.NORMAL,
    year: '2021-2023',
    sortYear: 2023,
    description: 'World editing module and metaverse system for the Space Creator project. Includes integrated video calling and real-time construction functionalities.',
    imageUrl: '/images/projects/space-creator-editor.jpg',
    techStack: ['Unity', 'Metaverse', 'World Editor', 'LiveKit', 'Multiplayer'],
    link: 'https://youtu.be/MaHYfF6BK-4'
  },
  {
    id: 'space-creator-customizer',
    title: 'Space Creator: Player Customizer',
    categories: [Category.VIDEOGAMES],
    importance: Importance.NORMAL,
    year: '2021-2022',
    sortYear: 2022,
    description: 'Avatar customization system for Space Creator. Allows players to modify their characters appearance in great detail within the metaverse environment.',
    imageUrl: '/images/projects/space-creator-customizer.jpg',
    techStack: ['Unity', 'UI/UX', 'Character System', 'Customization', 'C#'],
    link: 'https://youtu.be/wGYxoY61cMk'
  },
  {
    id: 'random-wars',
    title: 'Random Wars',
    categories: [Category.VIDEOGAMES],
    importance: Importance.CASUAL,
    year: '2015-2016',
    sortYear: 2016,
    description: 'Turn-based military strategy game for Android, with gameplay similar to Worms. Coordinated and partially developed project for mobile platforms.',
    imageUrl: '/images/projects/random-wars.jpg',
    techStack: ['Unity', 'Android', 'Turn-Based', 'Strategy', 'Mobile', 'C#'],
    link: 'https://youtu.be/DUc30EN0Nww'
  },
  {
    id: 'manifiest-simulator',
    title: 'Manifiest Simulator',
    categories: [Category.VIDEOGAMES, Category.SIMULATION],
    importance: Importance.CASUAL,
    year: '2012-2014',
    sortYear: 2014,
    description: 'My first project: Simulator of demonstrations and crowd dynamics. An experimental project that models the behavior of crowds in urban environments.',
    imageUrl: '/images/projects/manifiest-simulator.jpg',
    techStack: ['Unity', 'Protest Simulation', 'Physics', 'Experimental'],
    link: 'https://youtu.be/do2Uk3Ov0AM'
  },
  {
    id: 'surevil-vinyl',
    title: 'Surevil',
    categories: [Category.EXTENDED_REALITY],
    importance: Importance.CASUAL,
    year: '2004-2011',
    sortYear: 2007,
    description: 'Surevil, a company dedicated to the manufacturing of vinyl records. An industrial entrepreneurship project highlighted in the media (Noticias de la 2).',
    imageUrl: '/images/projects/surevil-vinyl.jpg',
    techStack: ['Entrepreneurship', 'Industrial', 'Vinyl', 'Manufacturing', 'Business'],
    link: 'https://youtu.be/vXTJh3ZwWks'
  },
  {
    id: 'space-creator',
    title: 'SPACE CREATOR',
    categories: [Category.VIDEOGAMES],
    importance: Importance.TOP,
    year: '2020-2025',
    sortYear: 2025,
    description: 'Multiplayer serious game for corporate team buildings. An immersive escape room experience that challenges teams to collaborate, solve puzzles, and think creatively under pressure.',
    imageUrl: '/images/projects/space-creator.jpg',
    techStack: ['Unity', 'Multiplayer', 'Serious Game', 'C#', 'Escape Room', 'LiveKit VoiceChat', 'Game Dev'],
    link: 'https://youtu.be/0Jp53uVpq-g?si=eXDNhAsuE1vU2qo8'
  },
  {
    id: 'npc-mcp',
    title: 'NPM MCP 2D GAME',
    categories: [Category.VIDEOGAMES, Category.ARTIFICIAL_INTELLIGENCE],
    importance: Importance.CASUAL,
    year: '2025',
    sortYear: 2025,
    description: '2D grid-based turn system where NPCs are directly controlled by a Large Language Model (LLM). The NPCs are equipped with the "superpowers" of a tool based on the Model Context Protocol (MCP).',
    imageUrl: '/images/projects/npc-mcp.jpg',
    techStack: ['Unity', 'LLM', 'MCP', '2D', 'Grid', 'Game Dev', 'AI NPC'],
    link: 'https://github.com/yeagob/NPC-MCP-2D-GAME'
  },
  {
    id: 'football',
    title: 'MULTIPLAYER FOOTBAL GAME',
    categories: [Category.VIDEOGAMES],
    importance: Importance.NORMAL,
    year: '2022',
    sortYear: 2022,
    description: 'Third-person multiplayer soccer game, multiplayer server development, solving ball synchronization between realities, and Unity 3D gameplay implementation.',
    imageUrl: '/images/projects/football.jpg',
    techStack: ['Unity', 'GameDev', 'Multiplayer', 'C#', 'Mirror Network'],
    link: 'https://youtu.be/6xkC6qCAfmA'
  },
  {
    id: 'vertex-killer',
    title: 'VERTEX KILLER',
    categories: [Category.SIMULATION, Category.VIDEOGAMES],
    importance: Importance.NORMAL,
    year: '2021',
    sortYear: 2021,
    description: 'Avatar character vertex elimination system, creation of a Unity Editor tool that allowed associating geometry elimination on the avatar with a piece of clothing to prevent clipping.',
    imageUrl: '/images/projects/vertex-killer.jpg',
    techStack: ['Unity', 'Dinamic Mesh', 'GameDev', 'Avatar'],
    link: 'https://www.youtube.com/watch?v=VRjfXCRUAlE'
  },
  {
    id: 'digital-asphalt',
    title: 'DIGITAL ASPHALT LAB',
    categories: [Category.SIMULATION],
    importance: Importance.TOP,
    year: '2018-2022',
    sortYear: 2022,
    description: 'Digital twin laboratory for civil engineering. Visualizes asphalt composition and stress tests using advanced physics simulation and machine learning for material analysis.',
    imageUrl: '/images/projects/digital-asphalt.jpg',
    techStack: ['Unity', 'Physics', 'Digital Twin', 'Machine Learning', 'Materials'],
    link: 'https://www.youtube.com/watch?v=VYWeSJ3niNw'
  },
  {
    id: 'realistic-car',
    title: 'REALISTIC CAR SIMULATION',
    categories: [Category.SIMULATION],
    importance: Importance.NORMAL,
    year: '2024',
    sortYear: 2024,
    description: 'High-fidelity physics and rendering simulation engine. Features advanced tire friction models, suspension dynamics, and HDRP photorealistic graphics.',
    imageUrl: '/images/projects/realistic-car.jpg',
    techStack: ['Unity 3D', 'SUMO', 'HDRP', 'C#', 'Vehicle Dynamics', 'RoadRunner'],
    link: 'https://youtu.be/cDg9jP5xoeQ'
  },
  {
    id: 'factory-robot',
    title: 'FACTORY LLM ROBOT ARM',
    categories: [Category.ARTIFICIAL_INTELLIGENCE, Category.SIMULATION],
    importance: Importance.CASUAL
    ,
    year: '2025',
    sortYear: 2025,
    description: 'Robotic arm controlled by machine learning in Python. Real-time physics simulation in Unity with socket communication for autonomous learning and factory automation.',
    imageUrl: '/images/projects/factory-robot.jpg',
    techStack: ['Python', 'Machine Learning', 'Physics', 'Sockets', 'Unity', 'Robotics'],
    link: 'https://github.com/yeagob/python_to_unity_robot'
  },
  {
    id: 'dragons',
    title: 'HERE BE DRAGONS',
    categories: [Category.EXTENDED_REALITY],
    importance: Importance.TOP,
    year: '2020',
    sortYear: 2021,
    description: 'Immersive XR experience featuring interactive dragon encounters. With stunning visual, light and audio effects in extended reality environments.',
    imageUrl: '/images/projects/dragons.jpg',
    techStack: ['Unity', 'XR', 'VFX', 'C#', 'Spatial Vision', 'Kinect'],
    link: 'https://www.youtube.com/watch?v=FI9n-p677VA'
  },
  {
    id: 'bromeliad',
    title: 'BROMELIAD',
    categories: [Category.VIDEOGAMES],
    importance: Importance.NORMAL,
    year: '2018-2020',
    sortYear: 2020,
    description: 'Published videogame on Steam. A unique gaming experience with innovative mechanics and immersive gameplay designed for players seeking challenge.',
    imageUrl: '/images/projects/bromelite.jpg',
    techStack: ['Unity', 'Steam', 'C#', 'Game Dev', 'Multiplayer'],
    link: 'https://store.steampowered.com/app/1366010/Bromeliad/'
  },
  {
    id: 'protest-simulator',
    title: 'PROTEST SIMULATOR',
    categories: [Category.SIMULATION],
    importance: Importance.CASUAL
    ,
    year: '2025',
    sortYear: 2025,
    description: 'Web application that transforms your daily steps into support for social causes. Walk for change and make every step count with gamified social impact.',
    imageUrl: '/images/projects/protest-simulator.jpg',
    techStack: ['Web App', 'Backend', 'Frontend', 'React', 'API', 'Node.js', 'Vite'],
    link: 'https://github.com/yeagob/manifiest2'
  },
];
